---
openapi: 3.1.1
info:
  title: foobar
  version: 0.1.0
servers:
  - url: /api
paths:
  /departments:
    get:
      summary: List departments
      description: Returns all the departments from the database
      operationId: listDepartments
      responses:
        "200":
          description: Returns the list of departments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfDepartments"
    post:
      summary: Create a new department
      operationId: createDepartment
      tags:
        - Departments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDepartmentRequest"
      responses:
        "201":
          description: The department was created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Department"
        "401":
          description: Unauthorized
        "409":
          description: Conflict - A department with this name already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConflictError"
components:
  schemas:
    Department:
      description: A department
      properties:
        id:
          type: integer
          description: The primary key of the department
        name:
          type: string
          description: The name of the department
          example: "Administration"
      required:
        - id
        - name
    PageOfDepartments:
      description: A single page of departments
      properties:
        departments:
          type: array
          items:
            $ref: "#/components/schemas/Department"
      required:
        - departments
    CreateDepartmentRequest:
      description: The request data required to create a department
      properties:
        name:
          description: The name of the department
          type: string
      required:
        - name
    ConflictError:
      description: Error response for conflicts
      properties:
        error:
          type: boolean
          example: true
        reason:
          type: string
          example: "A department with the name 'Human Resources' already exists"
      required:
        - error
        - reason
