---
openapi: 3.1.1
info:
  title: foobar
  version: 0.1.0
servers:
  - url: /api
paths:
  /departments:
    get:
      summary: List departments
      description: Returns all the departments from the database
      operationId: listDepartments
      responses:
        "200":
          description: Returns the list of departments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageOfDepartments"
components:
  schemas:
    Department:
      description: A department
      properties:
        id:
          type: integer
          description: The primary key of the department
        name:
          type: string
          description: The name of the department
          example: "Administration"
      required:
        - id
        - name
    PageOfDepartments:
      description: A single page of departments
      properties:
        departments:
          type: array
          items:
            $ref: "#/components/schemas/Department"
      required:
        - departments
